### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#489]
[AACAdditionPro] Unhandled exception number 8192 occured in onPacketSending(PacketEvent) for AACAdditionPro
java.lang.RuntimeException: Cannot retrieve entity from ID.
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:727) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:706) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:229) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:197) ~[?:?]
        at de.photon.aacadditionpro.protocol.packetwrappers.IWrapperPlayEntity.getEntity(IWrapperPlayEntity.java:41) ~[?:?]
        at de.photon.aacadditionpro.protocol.packetwrappers.IWrapperPlayEntity.getEntity(IWrapperPlayEntity.java:53) ~[?:?]
        at de.photon.aacadditionpro.modules.additions.EnchantmentHider.lambda$createModuleLoader$0(EnchantmentHider.java:44) ~[?:?]
        at de.photon.aacadditionpro.protocol.PacketAdapterBuilder$3.onPacketSending(PacketAdapterBuilder.java:89) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:535) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:516) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:346) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:308) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:433) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:373) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacket(NMSImpl.java:1437) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacketsNearby(NMSImpl.java:1461) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacketsNearby(NMSImpl.java:1467) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:457) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:136) ~[?:?]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1036) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:298) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 372.
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:265) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[?:?]
        ... 38 more
Caused by: java.lang.IllegalArgumentException: Unable to find a field that matches {modifiers=[required: 0, banned: 0], type=Exact class net.minecraft.server.v1_12_R1.Entity}
        at com.comphenix.protocol.reflect.FuzzyReflection.getField(FuzzyReflection.java:460) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.lambda$getEntityFromID$0(EntityUtilities.java:255) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
        at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:246) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:851) ~[?:?]
        at com.comphenix.protocol.wrappers.BukkitConverters$11.getSpecific(BukkitConverters.java:721) ~[?:?]
        ... 38 more

**Comment by Photon-GitHub** [comment]
Please include server and AACAdditionPro version in bug / error reports.

**Comment by Regomy** [comment]
> Please include server and AACAdditionPro version in bug / error reports.

 git-Paper-1618 (MC: 1.12.2)

**Comment by Photon-GitHub** [comment]
Does this also happen when Cititzens is not installed?

**Comment by Photon-GitHub** [comment]
Closed due to inactivity. Feel free to reopen if the issue persits.
