### ISSUE TITLE
[ERROR] packet

### ISSUE THREAD

**Issue by dogi-dogi** [Photon-GitHub/AntiCheatAddition#491]
v 1.12.2
paper spigot

--------------------------------------------------------------------------
[15:35:34 ERROR]: [AACAdditionPro] Unhandled exception number 2048 occured in onPacketSending(PacketEvent) for AACAdditionPro
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at de.photon.aacadditionpro.protocol.packetwrappers.sentbyserver.equipment.LegacyServerEquipmentWrapper.<init>(LegacyServerEquipmentWrapper.java:30) ~[?:?]
        at de.photon.aacadditionpro.protocol.packetwrappers.sentbyserver.equipment.IWrapperPlayEquipment.of(IWrapperPlayEquipment.java:24) ~[?:?]
        at de.photon.aacadditionpro.modules.additions.EnchantmentHider.lambda$createModuleLoader$0(EnchantmentHider.java:43) ~[?:?]
        at de.photon.aacadditionpro.protocol.PacketAdapterBuilder$3.onPacketSending(PacketAdapterBuilder.java:89) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203) ~[Paper.jar:git-Paper-1618]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacket(NMSImpl.java:1438) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacketsNearby(NMSImpl.java:1462) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacketsNearby(NMSImpl.java:1468) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:470) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:147) ~[?:?]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[Paper.jar:git-Paper-1618]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1015) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:318) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[15:35:52 ERROR]: [AACAdditionPro] Unhandled exception number 4096 occured in onPacketSending(PacketEvent) for AACAdditionPro
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/Pair
        at de.photon.aacadditionpro.protocol.packetwrappers.sentbyserver.equipment.LegacyServerEquipmentWrapper.<init>(LegacyServerEquipmentWrapper.java:30) ~[?:?]
        at de.photon.aacadditionpro.protocol.packetwrappers.sentbyserver.equipment.IWrapperPlayEquipment.of(IWrapperPlayEquipment.java:24) ~[?:?]
        at de.photon.aacadditionpro.modules.additions.EnchantmentHider.lambda$createModuleLoader$0(EnchantmentHider.java:43) ~[?:?]
        at de.photon.aacadditionpro.protocol.PacketAdapterBuilder$3.onPacketSending(PacketAdapterBuilder.java:89) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:336) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203) ~[Paper.jar:git-Paper-1618]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacket(NMSImpl.java:1438) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacketsNearby(NMSImpl.java:1462) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.sendPacketsNearby(NMSImpl.java:1468) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:470) ~[?:?]
        at net.citizensnpcs.nms.v1_12_R1.entity.EntityHumanNPC.B_(EntityHumanNPC.java:147) ~[?:?]
        at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1797) ~[Paper.jar:git-Paper-1618]
        at net.citizensnpcs.nms.v1_12_R1.util.NMSImpl.tick(NMSImpl.java:1015) ~[?:?]
        at net.citizensnpcs.util.NMS.tick(NMS.java:318) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:36) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[Paper.jar:git-Paper-1618]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[Paper.jar:git-Paper-1618]
        at java.lang.Thread.run(Thread.java:834) [?:?]

[15:35:58 WARN]: [AACAdditionPro] Plugin AACAdditionPro v7.3.2 generated an exception while executing task 61
java.lang.NoClassDefFoundError: org/bukkit/generator/WorldInfo
        at de.photon.aacadditionpro.util.execute.Placeholders$WorldPlaceholders.<clinit>(Placeholders.java:138) ~[?:?]
        at de.photon.aacadditionpro.util.execute.Placeholders.replacePlaceholders(Placeholders.java:71) ~[?:?]
        at de.photon.aacadditionpro.util.violationlevels.threshold.Threshold.executeCommandList(Threshold.java:35) ~[?:?]
        at de.photon.aacadditionpro.util.violationlevels.threshold.MultiThresholds.executeThresholds(MultiThresholds.java:28) ~[?:?]
        at de.photon.aacadditionpro.util.violationlevels.ViolationManagement.punishPlayer(ViolationManagement.java:77) ~[?:?]
        at de.photon.aacadditionpro.util.violationlevels.ViolationLevelManagement.addVL(ViolationLevelManagement.java:62) ~[?:?]
        at de.photon.aacadditionpro.util.violationlevels.ViolationLevelManagement.flag(ViolationLevelManagement.java:34) ~[?:?]
        at de.photon.aacadditionpro.modules.checks.pingspoof.Pingspoof.lambda$enable$0(Pingspoof.java:87) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[Paper.jar:git-Paper-1618]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[Paper.jar:git-Paper-1618]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.generator.WorldInfo
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109) ~[Paper.jar:git-Paper-1618]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[Paper.jar:git-Paper-1618]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]

**Comment by Janmm14** [comment]
Try to update ProtocolLib. Does this fix the issue?

**Comment by dogi-dogi** [comment]
> ProtocolLib 업데이트를 시도하십시오. 문제가 해결됩니까?
already update.
still error...

**Comment by Photon-GitHub** [comment]
Please update both your PaperSpigot as well as ProtocolLib.
Then, please post your PaperSpigot and ProtocolLib versions.

**Comment by Photon-GitHub** [comment]
Is this still happening?

**Comment by Photon-GitHub** [comment]
Closed due to inactivity. Feel free to reopen if this is still relevant.
