### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MViper** [Photon-GitHub/AntiCheatAddition#493]
Paper 1.18.2 

Console:
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Tried to define region with unknown world
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.0.1-jre.jar:?]
at de.photon.anticheataddition.util.minecraft.world.Region.<init>(Region.java:29) ~[AntiCheatAddition-8.0.0.jar:?]
at de.photon.anticheataddition.util.minecraft.world.Region.parseRegion(Region.java:53) ~[AntiCheatAddition-8.0.0.jar:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
at de.photon.anticheataddition.modules.checks.teaming.Teaming.<init>(Teaming.java:27) ~[AntiCheatAddition-8.0.0.jar:?]
at de.photon.anticheataddition.modules.ModuleManager.<clinit>(ModuleManager.java:101) ~[AntiCheatAddition-8.0.0.jar:?]
... 12 more

**Comment by Photon-GitHub** [comment]
Fixed in 8.0.1
