### ISSUE TITLE
NoClassDefFoundError: org/bukkit/generator/WorldInfo

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#501]
[17:02:56 WARN]: [AntiCheatAddition] Plugin AntiCheatAddition v8.0.4 generated an exception while executing task 530
java.lang.NoClassDefFoundError: org/bukkit/generator/WorldInfo
        at de.photon.anticheataddition.util.execute.Placeholders$WorldPlaceholders.<clinit>(Placeholders.java:118) ~[?:?]
        at de.photon.anticheataddition.util.execute.Placeholders.replacePlaceholders(Placeholders.java:65) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.threshold.Threshold.executeCommandList(Threshold.java:34) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.threshold.MultiThresholds.executeThresholds(MultiThresholds.java:27) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.ViolationManagement.punishPlayer(ViolationManagement.java:68) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.ViolationLevelManagement.addVL(ViolationLevelManagement.java:62) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.ViolationLevelManagement.flag(ViolationLevelManagement.java:34) ~[?:?]
        at de.photon.anticheataddition.modules.checks.pingspoof.Pingspoof.lambda$enable$0(Pingspoof.java:84) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.generator.WorldInfo
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 14 more
        
        PROTOCOLLIB VER: latest 4.8.0
        SERVER: [PAPERSPIGOT_1.16.5.jar:git-Paper-794]
        AntiCheatVer: 8.0.4
        
        
  java.lang.NoClassDefFoundError: Could not initialize class de.photon.anticheataddition.util.execute.Placeholders$WorldPlaceholders
        at de.photon.anticheataddition.util.execute.Placeholders.replacePlaceholders(Placeholders.java:65) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.threshold.Threshold.executeCommandList(Threshold.java:34) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.threshold.MultiThresholds.executeThresholds(MultiThresholds.java:27) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.ViolationManagement.punishPlayer(ViolationManagement.java:68) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.ViolationLevelManagement.addVL(ViolationLevelManagement.java:62) ~[?:?]
        at de.photon.anticheataddition.util.violationlevels.ViolationLevelManagement.flag(ViolationLevelManagement.java:34) ~[?:?]
        at de.photon.anticheataddition.modules.checks.pingspoof.Pingspoof.lambda$enable$0(Pingspoof.java:84) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?

**Comment by Photon-GitHub** [comment]
Might be fixed in 8.0.5, please check it out.

**Comment by Photon-GitHub** [comment]
Closed due to inactivity, feel free to reopen if the issue persists.
