### ISSUE TITLE
Error on player death (NullPointerException/entity is null)

### ISSUE THREAD

**Issue by kioging** [Photon-GitHub/AntiCheatAddition#516]
AntiCheatAddition(ACA) Version: 8.0.11
Server Version: 1.18.2
ProtocolLib Version: 5.0.0-b553
ACA Config: Default

[00:00:00] [Server thread/ERROR]: [AntiCheatAddition] Unhandled exception occurred in onPacketSending(PacketEvent) for AntiCheatAddition
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Entity.getEntityId()" because "entity" is null
	at de.photon.anticheataddition.modules.additions.EnchantmentHider.lambda$createModuleLoader$0(EnchantmentHider.java:59) ~[AntiCheatAddition-8.0.11.jar:?]
	at de.photon.anticheataddition.protocol.PacketAdapterBuilder.runPacketEventBiConsumer(PacketAdapterBuilder.java:101) ~[AntiCheatAddition-8.0.11.jar:?]
	at de.photon.anticheataddition.protocol.PacketAdapterBuilder$3.onPacketSending(PacketAdapterBuilder.java:138) ~[AntiCheatAddition-8.0.11.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib-b553.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib-b553.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:552) ~[ProtocolLib-b553.jar:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:526) ~[ProtocolLib-b553.jar:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:95) ~[ProtocolLib-b553.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:508) ~[ProtocolLib-b553.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.access$000(NettyChannelInjector.java:40) ~[ProtocolLib-b553.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.proxyRunnable(NettyChannelInjector.java:450) ~[ProtocolLib-b553.jar:?]
	at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:220) ~[ProtocolLib-b553.jar:?]
	at net.minecraft.network.Connection.writePacket(Connection.java:435) ~[?:?]
	at net.minecraft.network.Connection.send(Connection.java:382) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2039) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2025) ~[?:?]
	at net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:2293) ~[?:?]
	at net.minecraft.server.level.ChunkMap.broadcast(ChunkMap.java:2115) ~[paper-1.18.2.jar:git-Paper-289]
	at net.minecraft.server.level.ServerChunkCache.broadcast(ServerChunkCache.java:1171) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.handleEquipmentChanges(LivingEntity.java:3093) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.detectEquipmentUpdates(LivingEntity.java:3005) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2907) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:269) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:668) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:314) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:567) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1620) ~[paper-1.18.2.jar:git-Paper-289]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:483) ~[paper-1.18.2.jar:git-Paper-289]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1455) ~[paper-1.18.2.jar:git-Paper-289]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-289]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-289]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:00:00] [Server thread/ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutEntityEquipment@9c055a[
    b=776
    c=[(FEET, 1 iron_boots), (LEGS, 1 iron_leggings), (CHEST, 1 iron_chestplate), (HEAD, 1 iron_helmet)]
  ]

**Comment by Photon-GitHub** [comment]
Should be fixed in 8.1.0
