### ISSUE TITLE
Plugin erroring on startup ([STDERR] [java.util.logging.ErrorManager] java.util.logging.ErrorManager: 5)

### ISSUE THREAD

**Issue by PsychoLynx** [Photon-GitHub/AntiCheatAddition#531]
On a Purpur server (purpur-1.19-1668) with only AntiCheatAddition-8.2.4 and ProtocolLib-b569, the following error message is shown on startup:

[17:26:26] [Server thread/INFO]: [AntiCheatAddition] ViaVersion not found
[17:26:26] [Server thread/ERROR]: [STDERR] [java.util.logging.ErrorManager] java.util.logging.ErrorManager: 5
[17:26:26] [Server thread/WARN]: java.lang.StringIndexOutOfBoundsException: begin 20, end 19, length 19
[17:26:26] [Server thread/WARN]: 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
[17:26:26] [Server thread/WARN]: 	at java.base/java.lang.String.substring(String.java:2704)
[17:26:26] [Server thread/WARN]: 	at java.base/java.lang.String.substring(String.java:2677)
[17:26:26] [Server thread/WARN]: 	at AntiCheatAddition-8.2.4.jar//de.photon.anticheataddition.util.messaging.Log$1.format(Log.java:55)
[17:26:26] [Server thread/WARN]: 	at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:199)
[17:26:26] [Server thread/WARN]: 	at java.logging/java.util.logging.FileHandler.publish(FileHandler.java:769)
[17:26:26] [Server thread/WARN]: 	at java.logging/java.util.logging.Logger.log(Logger.java:980)
[17:26:26] [Server thread/WARN]: 	at java.logging/java.util.logging.Logger.doLog(Logger.java:1007)
[17:26:26] [Server thread/WARN]: 	at java.logging/java.util.logging.Logger.log(Logger.java:1030)
[17:26:26] [Server thread/WARN]: 	at java.logging/java.util.logging.Logger.info(Logger.java:1803)
[17:26:26] [Server thread/WARN]: 	at AntiCheatAddition-8.2.4.jar//de.photon.anticheataddition.AntiCheatAddition.checkForPlugin(AntiCheatAddition.java:76)
[17:26:26] [Server thread/WARN]: 	at AntiCheatAddition-8.2.4.jar//de.photon.anticheataddition.AntiCheatAddition.onEnable(AntiCheatAddition.java:120)
[17:26:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:26:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[17:26:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536)
[17:26:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554)
[17:26:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468)
[17:26:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[17:26:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[17:26:26] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:342)
[17:26:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1137)
[17:26:26] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307)
[17:26:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Photon-GitHub** [comment]
I am reasonably sure that this is an error in your server software or your java version. On normal spigot with the same configuration this problem does not exist. I would recommend you to update both your java (latest java 17 version) and your purpur. Otherwise I am pretty sure that ACA is not involved as I only call the bukkit logger with a string here, and the error is thrown somewhere inside this logging method.

**Comment by Janmm14** [comment]
> I am reasonably sure that this is an error in your server software or your java version. On normal spigot with the same configuration this problem does not exist. I would recommend you to update both your java (latest java 17 version) and your purpur. Otherwise I am pretty sure that ACA is not involved as I only call the bukkit logger with a string here, and the error is thrown somewhere inside this logging method.

Its your log handler throwing:
> at AntiCheatAddition-8.2.4.jar//de.photon.anticheataddition.util.messaging.Log$1.format(Log.java:55)

**Comment by Photon-GitHub** [comment]
That means that purpur does not log the same way as spigot does. Oh well, I will look into it.

**Comment by PsychoLynx** [comment]
Thank you kindly!

**Comment by Photon-GitHub** [comment]
If you want (and can compile ACA yourself), you can try the ACA version on 8.2.5 and check if it is still happening. It should be fixed there. @PsychoLynx
