### ISSUE TITLE
Error: Tried to check chunks between worlds

### ISSUE THREAD

**Issue by HenryXiaoYang** [Photon-GitHub/AntiCheatAddition#541]
Probably it's esp's error

[AntiCheatAddition] Plugin AntiCheatAddition v8.3.1 generated an exception while executing task 28
java.lang.IllegalArgumentException: Tried to check chunks between worlds.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
at de.photon.anticheataddition.util.minecraft.world.ModernWorldUtil.areChunksLoadedBetweenLocations(ModernWorldUtil.java:100) ~[AntiCheatAddition-8.3.1.jar:?]
at de.photon.anticheataddition.modules.additions.esp.SingleCameraCanSee.canSee(SingleCameraCanSee.java:38) ~[AntiCheatAddition-8.3.1.jar:?]
at de.photon.anticheataddition.modules.additions.esp.Esp.processWorldQuadTree(Esp.java:124) ~[AntiCheatAddition-8.3.1.jar:?]
at de.photon.anticheataddition.modules.additions.esp.Esp.lambda$enable$6(Esp.java:108) ~[AntiCheatAddition-8.3.1.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1858]
at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1858]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Photon-GitHub** [comment]
Should be fixed in 8.3.2, please recheck (and make sure to update ProtocolLib to the latest dev version).

**Comment by nuym** [comment]
8.3.2 works well, thank you.

**Comment by nuym** [comment]
well,If the player is switching the world to move, the ESP will flash, and the ESP will not be visible when the player is not moving

**Comment by nuym** [comment]
like this

https://user-images.githubusercontent.com/102905510/212470328-b0d528ff-4a35-427c-8b5f-9013f65040af.mp4

**Comment by Janmm14** [comment]
@nuym unfortunaly thats just an audio recording

**Comment by nuym** [comment]
> @nuym unfortunaly thats just an audio recording

hmmm wait

**Comment by nuym** [comment]
https://user-images.githubusercontent.com/102905510/212479583-8aa9919b-dc60-4a68-9622-88146099c4ea.mp4

**Comment by nuym** [comment]
You can click the three dots on the right to download the video locally, which seems to be a problem with github.

**Comment by nuym** [comment]
I send video to your discord

**Comment by nuym** [comment]
Is it yours?Janmm14#2661
this is my nuym#9917

**Comment by nuym** [comment]
also Photon#4667

**Comment by Janmm14** [comment]
https://cdn.discordapp.com/attachments/1063841091876569128/1063841863011926036/1673695575703.mp4

**Comment by Photon-GitHub** [comment]
I think that is more due to the fact that ACA does not check every single block between two players as that would cost too much performance. If there is only a one to three block wall separating the players over a large distance, ESP might not detect the wall, or only in some places, which could cause the flickering.

**Comment by nuym** [comment]
> I think that is more due to the fact that ACA does not check every single block between two players as that would cost too much performance. If there is only a one to three block wall separating the players over a large distance, ESP might not detect the wall, or only in some places, which could cause the flickering.

In fact, when the two players do not switch to the second world, the distance is about 50 frames, and the ACA can hide players as long as the two players have a few walls. Of course this is not quite in line with the original intent of AntiESP.Thank you for developing ACA!
Best Wishes
