### ISSUE TITLE
Support 1.20.6

### ISSUE THREAD

**Issue by envizar** [Photon-GitHub/AntiCheatAddition#598]
Paper 1.20.6 build 53, packetevents 2.3.0
```
[09:14:33 ERROR]: Error occurred while enabling AntiCheatAddition v9.0.1 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at AntiCheatAddition-9.0.1.jar/de.photon.anticheataddition.modules.additions.BrandHider.<clinit>(BrandHider.java:22) ~[AntiCheatAddition-9.0.1.jar:?]
        at AntiCheatAddition-9.0.1.jar/de.photon.anticheataddition.modules.ModuleManager.<clinit>(ModuleManager.java:46) ~[AntiCheatAddition-9.0.1.jar:?]
        at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
        at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68) ~[reflection-rewriter-runtime-0.0.1.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source) ~[paper-1.20.6.jar:git-Paper-53]
        at AntiCheatAddition-9.0.1.jar/de.photon.anticheataddition.AntiCheatAddition.mbmBMMbbMbmMBbMBbmbmbmMmmbmMmB(AntiCheatAddition.java) ~[AntiCheatAddition-9.0.1.jar:?]
        at AntiCheatAddition-9.0.1.jar/de.photon.anticheataddition.AntiCheatAddition.ΤκυχκΠΤγωζθΤλωΥΠΝοηγΞπλλλγΨσΝΡΨΝεΒαφΛλ(AntiCheatAddition.java) ~[AntiCheatAddition-9.0.1.jar:?]
        at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:92) ~[?:?]
        at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:316) ~[?:?]
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:274) ~[?:?]
        at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:264) ~[?:?]
        at AntiCheatAddition-9.0.1.jar/de.photon.anticheataddition.AntiCheatAddition.onEnable(AntiCheatAddition.java:153) ~[AntiCheatAddition-9.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-53]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-53]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-53]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-53]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at AntiCheatAddition-9.0.1.jar/de.photon.anticheataddition.util.reflection.Reflect.<clinit>(Reflect.java:14) ~[AntiCheatAddition-9.0.1.jar:?]
        ... 26 more
```

**Comment by Photon-GitHub** [comment]
at AntiCheatAddition-9.0.1.jar/de.photon.anticheataddition.AntiCheatAddition.mbmBMMbbMbmMBbMBbmbmbmMmmbmMmB(AntiCheatAddition.java) ~[AntiCheatAddition-9.0.1.jar:?]
        at AntiCheatAddition-9.0.1.jar/de.photon.anticheataddition.AntiCheatAddition.ΤκυχκΠΤγωζθΤλωΥΠΝοηγΞπλλλγΨσΝΡΨΝεΒαφΛλ(AntiCheatAddition.java) ~[AntiCheatAddition-9.0.1.jar:?]
        
        You use a cracked version of my plugin, that is your problem.
