### ISSUE TITLE
Serious Incompatibility Issues

### ISSUE THREAD

**Issue by Buttercuq** [Photon-GitHub/AntiCheatAddition#612]
When you install this plugin, it gives a huge warning message every time players enter and exit the game .

Server Version : purpur 1.17.1
Incompatible Plugins :  

Model-Engine-R3.1.11
TradeSystem_v2.5.3
TAB-Bridge v5.0.6
LPX (anti-crash etc..)
Eglow (I will uninstall eglow but be aware that it causes problems if some are using it.)
GSit

Plugin List :
[03:19:50 INFO]: Plugins (73): AdvanceParticle, AlphaChest, Announcer, AntiCaps,
 AntiCurse, AquaticCrates, BanItem, BetterProfiles, BroadcastPlus, Citizens, Cit
izensGUI, ClearLag, CommandForward, CommandNPC, DecentHolograms, DeluxeMenus, De
luxeWithdraw, DeluxeWithdrawVaultAddon, DisableVillagerTrade, DiscordSRV, Econom
yShopGUI-Premium, eGlow, Ersatz, Essentials, DMIH , GSit, HeadDr
ops, iKoth, InventoryFullPlus, ItemEdit, ItemsAdder, LeaderOS, LockettePro, Lone
Libs, LPX, LuckPerms, Matrix, ModelEngine, Multiverse-Core, MuteManager, MythicM
obs, NBTAPI, NexEngine, OreRegenerator, OrmanSistemi, Pl-Hide-Pro, PlaceholderAP
I, PlotSquared, ProtocolLib, PvPManager, ScreenEffects, Shopkeepers, SkBee, Skel
lett, SkinsRestorer, SkQuery, skRayFall, Skript, skUtilities, TAB-Bridge, TradeS
ystem, UltimateClans, Vault, Vegas, ViaVersion, VoidGen, Votifier, VotingPlugin,
 WebSender, WorldEdit, WorldGuard, Wraith, zAuctionHouseV3

[02:55:58] [User Authenticator #2/INFO]: UUID of player Buttercuq is f29fb58d-e02b-372f-b415-83ab237c1929
[02:55:58] [Netty Server IO #1/WARN]: [com.github.retrooper.packetevents.PacketEventsAPI] PacketEvents caught an unhandled exception while calling your listener.
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.Player.getUniqueId()" because "<parameter1>" is null
	at de.photon.anticheataddition.user.User.getUser(User.java:104) ~[AntiCheatAddition-9.1.2.jar:?]
	at de.photon.anticheataddition.user.User.getUser(User.java:99) ~[AntiCheatAddition-9.1.2.jar:?]
	at de.photon.anticheataddition.util.protocol.PacketAdapterBuilder.runPacketSendEventBiConsumer(PacketAdapterBuilder.java:103) ~[AntiCheatAddition-9.1.2.jar:?]
	at de.photon.anticheataddition.util.protocol.PacketAdapterBuilder$3.onPacketSend(PacketAdapterBuilder.java:145) ~[AntiCheatAddition-9.1.2.jar:?]
	at com.github.retrooper.packetevents.event.PacketSendEvent.call(PacketSendEvent.java:51) ~[packetevents-spigot-2.3.0.jar:?]
	at com.github.retrooper.packetevents.event.EventManager.callEvent(EventManager.java:52) ~[packetevents-spigot-2.3.0.jar:?]
	at com.github.retrooper.packetevents.util.PacketEventsImplHelper.handleClientBoundPacket(PacketEventsImplHelper.java:44) ~[packetevents-spigot-2.3.0.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.handleClientBoundPacket(PacketEventsEncoder.java:82) ~[packetevents-spigot-2.3.0.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:67) ~[packetevents-spigot-2.3.0.jar:?]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.encode(PacketEventsEncoder.java:46) ~[packetevents-spigot-2.3.0.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.github.retrooper.packetevents.injector.handlers.PacketEventsEncoder.write(PacketEventsEncoder.java:101) ~[packetevents-spigot-2.3.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110) ~[patched_1.17.1.jar:git-Purpur-1428]
	at it.ytnoos.lpx.o7.write(o7.java) ~[LPX v3.4.6.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Purpur-1428]
	at me.neznamy.tab.bridge.bukkit.BridgeChannelDuplexHandler.write(BridgeChannelDuplexHandler.java:31) ~[TAB-Bridge v5.0.6.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Purpur-1428]
	at dev.geco.gsit.mcv.v1_17_1.util.PackageUtil$1.write(PackageUtil.java:73) ~[GSit-1.6.0.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Purpur-1428]
	at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:77) ~[TradeSystem_v2.5.3.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Purpur-1428]
	at de.codingair.tradesystem.lib.codingapi.player.data.PacketReader$1.write(PacketReader.java:77) ~[TradeSystem_v2.5.3.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Purpur-1428]
	at me.mrgraycat.eglow.util.packets.PipelineInjector$1.write(PipelineInjector.java:109) ~[eGlow 3.2.8 1.9.4-1.20.4.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.1.jar:git-Purpur-1428]
	at com.ticxo.modelengine.nms.v1_17_R1.network.ModelEngineChannelHandler.write(ModelEngineChannelHandler.java:66) ~[Model-Engine-R3.1.11.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Purpur-1428]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
[02:55:58] [Server thread/INFO]: Buttercuq[/127.0.0.1:64875] logged in with entity id 527 at ([spawn]-23.5, 60.0, -7.5)
[02:55:58] [Server thread/INFO]: [Matrix] (Via) Player Buttercuq joined with (1.17.x/756) client

**Comment by Photon-GitHub** [comment]
Fixed in 9.1.3

**Comment by Buttercuq** [comment]
> 9.1.3'te düzeltildi

thx bro <3
