### ISSUE TITLE
🟡 | Error with jump boost potion in TowerBatchProcessor

### ISSUE THREAD

**Issue by Regomy** [Photon-GitHub/AntiCheatAddition#649]
```
[22:25:58 INFO]: Rejomy issued server command: /effect Rejomy minecraft:jump_boost 100 10
[22:25:58 INFO]: [Rejomy: Given Jump Boost (ID 8) * 10 to Rejomy for 100 seconds]
[22:26:04 WARN]: Exception in thread "pool-33-thread-1"
[22:26:04 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getBlockAt(org.bukkit.Location)" because "this.world" is null

[22:26:04 WARN]:        at org.bukkit.Location.getBlock(Location.java:87)

[22:26:04 WARN]:        at de.photon.anticheataddition.modules.checks.tower.TowerBatchProcessor.simulateJumpBoost(TowerBatchProcessor.java:96)

[22:26:04 WARN]:        at de.photon.anticheataddition.modules.checks.tower.TowerBatchProcessor.calculateDelay(TowerBatchProcessor.java:83)

[22:26:04 WARN]:        at de.photon.anticheataddition.modules.checks.tower.TowerBatchProcessor.lambda$processBatch$0(TowerBatchProcessor.java:38)

[22:26:04 WARN]:        at de.photon.anticheataddition.util.datastructure.batch.BatchPreprocessors.zipReduceToDoubleStatistics(BatchPreprocessors.java:87)

[22:26:04 WARN]:        at de.photon.anticheataddition.modules.checks.tower.TowerBatchProcessor.processBatch(TowerBatchProcessor.java:37)

[22:26:04 WARN]:        at de.photon.anticheataddition.util.datastructure.batch.AsyncBatchProcessor.lambda$receive$0(AsyncBatchProcessor.java:25)

[22:26:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

[22:26:04 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

[22:26:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)

```

[22:29:51 INFO]: This server is running PandaSpigot version git-PandaSpigot-"858ab0f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 858ab0f)
[22:29:51 INFO]: Checking version, please wait...
[22:29:52 INFO]: You are running the latest version

[22:29:57 INFO]: [AntiCheatAddition] Version: 9.1.4

**Comment by Photon-GitHub** [comment]
Fixed in 9.1.5
