### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by jhqwqmc** [Photon-GitHub/AntiCheatAddition#654]
Error enabling plugin
```log
[17:15:06 INFO]: [AntiCheatAddition] Enabling AntiCheatAddition v9.1.6
[17:15:07 INFO]: [AntiCheatAddition] Logging setup finished. Console: INFO | File: FINE | Player: OFF
[17:15:07 ERROR]: Error occurred while enabling AntiCheatAddition v9.1.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at AntiCheatAddition-9.1.6.jar/de.photon.anticheataddition.AntiCheatAddition.lambda$onEnable$2(AntiCheatAddition.java:114) ~[AntiCheatAddition-9.1.6.jar:?]
        at java.logging/java.util.logging.Logger.log(Logger.java:1054) ~[?:?]
        at java.logging/java.util.logging.Logger.info(Logger.java:1914) ~[?:?]
        at AntiCheatAddition-9.1.6.jar/de.photon.anticheataddition.util.log.Log.info(Log.java:54) ~[AntiCheatAddition-9.1.6.jar:?]
        at AntiCheatAddition-9.1.6.jar/de.photon.anticheataddition.AntiCheatAddition.onEnable(AntiCheatAddition.java:114) ~[AntiCheatAddition-9.1.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:693) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:455) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:361) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2247-39617d5]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: de.photon.anticheataddition.exception.UnknownMinecraftException: Unknown minecraft version.
        at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at AntiCheatAddition-9.1.6.jar/de.photon.anticheataddition.ServerVersion.<clinit>(ServerVersion.java:54) ~[AntiCheatAddition-9.1.6.jar:?]
        ... 17 more
[17:15:07 INFO]: [AntiCheatAddition] Disabling AntiCheatAddition v9.1.6
[17:15:07 INFO]: [AntiCheatAddition] AntiCheatAddition disabled.
[17:15:07 INFO]: [AntiCheatAddition]
```

**Comment by Photon-GitHub** [comment]
Implemented in 9.1.7
